/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 30.11.2025 06:51:13

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1424;
#else
constexpr int kTensorArenaSize = 400;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,35 } };
const TfArray<1, float> quant0_scale = { 1, { 10.376470565795898, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[9] = { -1, 0, 7, -7, 5, 7, 5, -6, 5, };
const TfArray<1, int> tensor_dimension1 = { 1, { 9 } };
const TfArray<1, float> quant1_scale = { 1, { 0.015502713620662689, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[9*16] = { 
  42, -62, 51, 58, 37, 12, 11, 69, -67, -66, 49, 2, 39, 63, 40, -34, 
  40, -51, 30, -16, 5, 33, -45, -25, 28, 68, 43, 27, 62, 13, -127, -57, 
  -63, 0, -40, 26, -44, 30, 5, 47, -75, 57, 22, -3, 13, 49, 11, 31, 
  17, -29, -69, 42, -68, -26, 24, 85, -67, -60, -83, -72, -74, -50, 12, 63, 
  49, -76, -76, -23, 30, 47, 32, 25, -8, -5, -50, -41, -70, 20, -41, -42, 
  -8, -69, -46, 80, 68, 13, 66, 47, 77, 46, 17, 72, 44, 4, 53, -30, 
  87, 35, -62, -27, 45, -62, -71, 33, 51, -32, 17, -28, -71, -58, 45, -32, 
  -13, 7, -6, 37, -16, 72, 39, -31, 72, -55, 63, -60, -48, -31, -74, 39, 
  90, -61, 83, -59, 6, -5, 63, -54, 32, 25, -41, 65, 59, -71, 49, -41, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 9,16 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0059876558370888233, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[16] = { -2, 0, 0, -2, 3, -1, 0, -1, -2, 6, -1, -2, -1, 0, 4, -5, };
const TfArray<1, int> tensor_dimension3 = { 1, { 16 } };
const TfArray<1, float> quant3_scale = { 1, { 0.022262036800384521, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[16*32] = { 
  40, 47, 104, 77, -32, -10, 2, 52, -5, 24, 0, -18, -75, 15, 85, -108, 34, 56, 25, 34, -96, -53, 69, 3, 8, 51, 98, 85, 66, -26, -4, -115, 
  -55, 90, 3, 79, -7, -92, -30, 48, -74, -24, -49, 5, 83, 110, 64, 109, 95, 18, 33, -109, -58, -74, -3, -1, 17, 46, 64, -31, -110, -97, 103, -46, 
  -22, 40, -42, 14, 15, -24, 12, 62, 112, 9, 83, 70, 65, -92, 0, 110, -86, 51, 54, -61, -34, 10, 87, -1, 105, 85, -50, 8, -89, 37, 103, 83, 
  58, -71, 50, -55, 72, -28, -92, 45, 22, -99, -26, 88, -10, -73, -63, 32, -76, 4, -45, -55, 52, -28, 68, 51, 74, -85, 52, -9, -13, -93, -85, -18, 
  -45, -67, -77, -73, -115, -92, 23, 30, -85, -34, -48, -70, -41, 63, 30, -24, 58, 75, 76, -59, -94, 105, -36, 21, -110, -59, -32, 36, 51, 63, 104, -67, 
  -87, 67, 61, 48, -53, -111, -52, 79, -93, 55, -36, -44, 55, 65, -96, -32, -69, 114, 57, 24, 6, 16, -76, 60, -60, 66, -9, -23, 28, -47, -49, -84, 
  91, -3, 40, 69, -103, -26, 32, 21, 49, -81, 59, -99, -32, -8, 25, 66, -39, -108, -71, 78, -19, 22, -85, -85, -69, -29, 104, -42, -99, 40, -74, -43, 
  -15, 93, -2, -107, -96, 82, 98, 49, 62, 88, 85, 104, 72, 82, 53, 65, 16, 3, -71, -18, 101, 37, 105, 39, -10, 99, -19, -108, 79, -49, 67, 30, 
  62, -95, 98, 69, 11, -29, 89, 53, -40, -69, -86, 72, 80, -38, -115, 107, -24, -56, 80, 55, 17, 57, -31, -20, 20, -119, 112, -2, -20, -124, 71, -50, 
  43, -69, 53, 77, -53, 83, 77, 52, -27, -44, -18, -67, -3, 53, -33, 41, -8, -68, -47, 88, -31, 51, -42, 91, -4, 98, -76, -87, -81, 88, -17, 96, 
  -76, -58, -48, 24, 20, -72, 62, -29, -104, -94, -26, -16, -58, -110, -79, 31, -60, -8, -46, 46, -77, 52, -33, 93, -1, 18, -22, 91, 14, 46, 78, 40, 
  -113, 46, -65, 85, 58, 5, -58, -88, -53, -67, 34, 13, 94, -127, -7, 40, -32, -12, -89, 58, -96, -102, -86, -45, 86, 69, 41, -90, 55, -99, 43, -120, 
  -95, 54, -84, 96, -55, -29, 94, -38, 54, -17, -96, -47, -117, 48, -96, -38, 61, 60, 72, 9, 50, -107, -60, 45, -125, -91, -47, -33, 12, 43, 16, 10, 
  13, -16, -30, -51, -109, 72, -59, -50, 69, 49, -53, 3, -112, -95, -60, -87, -51, 18, 103, -5, 79, -90, -79, 68, -20, 9, 4, -97, 78, -63, 13, -3, 
  59, 13, 79, -24, -21, 60, 19, -67, -13, 94, 99, 24, -11, -13, 62, -78, 92, -111, 14, 112, 19, -98, 3, -93, 113, -63, -56, -45, -104, 110, 11, -77, 
  69, 66, -11, -49, 6, -39, -52, 66, -4, -18, 61, -30, 8, -62, 10, 40, -66, -89, 71, -69, -109, -16, 24, 60, 39, -41, 56, -68, 17, 102, -18, 59, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 16,32 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0030667691025882959, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[32] = { 0, 0, 0, 0, -3, -2, 0, -1, 0, 0, 0, 0, -2, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, -1, 0, 1, -3, 0, -3, 1, 0, -2, };
const TfArray<1, int> tensor_dimension5 = { 1, { 32 } };
const TfArray<1, float> quant5_scale = { 1, { 0.048656389117240906, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[32*35] = { 
  0, -60, -40, 51, -7, 21, 30, 11, 15, 10, 16, -21, -15, -53, 56, -58, -20, 43, -44, 35, 38, 57, -31, 19, -42, 28, 10, -23, -7, -22, -41, 63, 46, -12, 32, 
  -62, -64, -3, 46, -58, 28, 15, -23, -22, -40, 49, -10, 5, 34, 12, 32, -63, -9, -5, -28, 54, -61, -59, 60, -9, -26, 31, -17, 19, 41, 5, 38, -9, 58, -38, 
  41, -54, -35, 31, 37, 60, 21, -5, -54, 30, 20, 8, 49, -32, -58, 8, -38, -52, -57, -61, 32, 39, 37, 18, -50, 32, 51, 3, 2, 4, 22, -27, 52, 28, 45, 
  -60, 45, 46, -19, 65, 11, 16, 53, 36, -31, -55, -35, 32, -14, 70, 48, 10, 27, 83, -33, 60, 34, -58, -56, 18, -16, -26, 63, 0, 14, 37, 44, -17, -54, 54, 
  55, -36, -8, 35, -66, 5, -8, 42, -37, -19, 40, -115, 60, -22, -70, -50, -51, -36, -59, 31, 69, -62, -42, 21, -77, -73, 0, -14, 52, 58, -12, -25, -62, -14, -10, 
  -17, 33, -3, 12, -55, 0, 15, -40, 15, -9, -54, 21, 29, -6, -20, 29, -66, 2, -51, 24, 49, 1, 5, -20, 37, -20, -11, 20, -17, -3, -2, 31, 60, -24, 75, 
  31, -16, -61, -33, -28, -22, -22, 19, 30, -62, -25, -37, 14, -59, -32, -25, -55, -20, -49, 63, 1, -57, 56, -4, 50, -7, 13, -20, -12, -24, -6, -58, -39, -1, -48, 
  32, 33, -33, 22, 8, -44, 52, 37, 18, 9, -42, -93, -41, 41, -54, -16, 0, 29, 43, 37, 39, -50, -24, -71, 6, 14, -56, 3, -49, -57, -37, 2, 43, -63, 32, 
  35, -14, -20, -47, -21, -5, -2, -59, -28, -22, 26, -30, -17, 58, 24, 39, -31, -31, -50, 23, -9, -59, 39, -58, -28, -32, -47, -31, -39, 49, -33, -11, -56, -16, -9, 
  -53, 51, -3, -50, -25, -35, -40, 17, 29, -45, -7, 64, -24, -52, -47, 64, -11, 54, 62, -8, -46, 43, 15, -37, 44, 14, 61, -46, -62, 6, 54, -57, 29, -26, 18, 
  61, -54, 12, -62, -41, -4, -48, -63, 37, -47, -1, 1, -50, 12, -35, 52, 60, -52, 16, 29, -50, -12, -42, 26, -49, 24, -59, 41, -54, 64, 37, 32, 28, 39, 40, 
  -9, -33, -60, 18, 19, 46, 51, 24, 25, -1, -26, 21, 37, -41, 50, 19, -45, -23, -9, -44, 3, 38, 13, 17, 4, 28, 1, -45, -6, -59, -55, -41, -5, 10, 29, 
  -31, 8, -6, 37, -36, -32, 0, -30, -33, 45, -2, -23, -6, 46, -4, 17, 31, 34, -73, 71, -42, -36, -49, 38, -56, -51, -63, 51, 19, 55, -9, 40, -8, -40, 56, 
  2, -3, 33, 24, 55, -39, -106, 51, -27, -44, -74, 43, -87, 55, 17, 2, 46, 49, 55, -5, -40, 32, 80, 66, -11, 127, -54, -25, -63, -44, 63, 55, -37, -60, -90, 
  57, -23, -62, -25, 53, 30, -2, -24, -49, 44, -56, 62, 24, 29, -49, -60, 63, -18, 43, 41, -29, -49, 50, -49, -48, -63, -5, 33, 44, -50, -62, -42, -54, -4, -52, 
  0, 18, -31, -56, 61, 23, -14, 50, 58, -14, 10, -43, 17, -14, -24, 14, -18, -27, 24, 26, -23, -23, 22, 16, 43, 36, 63, 35, -20, -40, -46, -43, 29, 21, -48, 
  1, 38, 18, -55, -15, 23, 4, -56, 34, 34, -50, 62, 54, 36, -10, 26, 45, -44, -17, -41, 49, -52, -39, -42, 36, 0, -57, -54, -25, 38, -5, -58, 25, 12, 60, 
  -12, -54, -18, 61, 63, 22, -54, 8, 17, -1, -44, 45, -11, -50, -32, -34, 3, -15, 5, -6, 2, 44, -50, -5, 55, -60, -34, 36, -31, -42, -48, 33, 2, -30, 38, 
  -53, 29, 27, -38, 45, -2, -48, -46, 61, -10, 4, 22, 63, 61, 41, -28, -30, -32, -18, -59, -40, 63, -54, 14, 63, -46, 3, 23, 39, -34, -50, -20, -11, -11, -7, 
  -9, 48, -12, 10, 54, 37, 28, 28, 27, -64, -4, 17, -80, 65, 23, 20, 64, 77, 37, 13, 74, 24, 68, -52, -15, -12, 58, 50, -39, -54, -6, -47, -12, 54, -55, 
  -9, 1, -50, -15, -37, -50, -15, -40, 31, -27, 45, 53, -7, -37, 26, 40, 4, -58, 46, -60, -52, 39, -20, -54, 6, -6, -51, 35, -51, -8, -45, 42, -49, -46, 30, 
  -4, -35, -21, -20, 0, 58, 12, -62, 45, 50, 31, -51, -49, -27, 59, 30, -43, -30, -37, -18, 61, -9, 43, -34, 9, -35, 52, 11, -42, 26, 0, 21, 21, 33, 12, 
  -8, -34, -39, 5, 10, -5, 61, 1, -45, -37, 37, 36, -30, 53, 49, -16, -9, 51, -44, -50, -45, -10, -57, -43, 18, 33, -61, -31, -10, -60, -16, -13, -54, -36, 56, 
  25, -55, 47, -29, -31, -57, 3, -30, -8, 21, -38, 15, 55, -51, -5, 24, -36, -68, 44, -21, -20, -13, -19, 6, 26, 31, 18, 30, -51, 29, 29, 26, -12, 22, 44, 
  17, -21, -50, 22, -69, 56, -63, 42, -9, 52, 46, 16, 66, 36, 38, 2, -12, 51, 47, -6, -53, -7, -44, 6, -28, 15, 7, -61, -22, 36, 42, 5, 63, -53, -67, 
  38, 46, -45, 10, 97, -5, -45, -68, 34, -49, 14, 28, -35, 66, 3, 7, -9, 22, 43, -56, -2, 5, 42, 16, -20, 48, 45, -32, 47, 36, 40, -29, -61, -8, -37, 
  -12, 42, -46, 45, -25, 16, -11, 26, -28, -16, -23, -7, -27, 23, 2, -50, -46, 1, -82, 28, -16, 40, -40, 14, -81, -41, -51, -2, -33, -41, -13, 3, -12, 33, -8, 
  -62, 3, -48, -6, 10, 53, -51, 40, 27, 49, -34, -34, -14, -41, 28, 60, -41, 64, -28, -22, -55, 5, -44, 12, 56, 18, 17, -33, -3, -16, 31, 16, 19, 15, -36, 
  49, 41, 26, 41, -91, -36, 58, -1, -60, 7, -46, 24, 25, -2, -70, -3, -74, 10, -63, 44, 3, -2, 22, -16, -27, -48, -30, -33, 46, -58, 19, -59, -63, -17, -30, 
  20, -2, 49, -2, 83, -34, 8, 46, 2, -31, 28, -69, -25, -1, 79, 59, 62, 6, 41, -121, -9, -5, 43, 41, -38, 13, 82, 42, -47, 60, -49, -7, -47, 28, -59, 
  15, -45, 4, -21, -6, 21, 10, -54, 25, -33, -1, 27, 53, -28, 50, -11, 31, 49, 42, -27, -14, -21, -51, -51, -21, -8, -10, -10, 61, 14, 24, -14, 20, 20, -45, 
  24, 40, -56, 20, -4, 18, 75, -26, -31, -16, -12, 46, 33, -35, -64, 11, 24, -26, -24, 2, -37, -3, -11, 32, -19, -13, 68, 49, 13, 17, -6, -2, 45, -20, -17, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 32,35 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0046891076490283012, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,32 } };
const TfArray<1, float> quant7_scale = { 1, { 7.2591171264648438, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,16 } };
const TfArray<1, float> quant8_scale = { 1, { 2.5891122817993164, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,9 } };
const TfArray<1, float> quant9_scale = { 1, { 1.594904899597168, } };
const TfArray<1, int> quant9_zero = { 1, { -54 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 35, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 36, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 512, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1120, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 48), (TfLiteIntArray*)&g0::tensor_dimension7, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 9, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 9, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_827660_5_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_827660_5_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_827660_5_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_827660_5_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_827660_5_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
