/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 30.11.2025 08:33:20

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1424;
#else
constexpr int kTensorArenaSize = 400;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,35 } };
const TfArray<1, float> quant0_scale = { 1, { 10.486274719238281, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[9] = { 12, 2, 30, -33, 0, 28, -2, -14, 3, };
const TfArray<1, int> tensor_dimension1 = { 1, { 9 } };
const TfArray<1, float> quant1_scale = { 1, { 0.0097967032343149185, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[9*16] = { 
  62, -75, 70, 69, 52, 14, 13, 73, -84, -80, 41, 4, 47, 76, 48, -32, 
  53, -62, 16, -19, 9, 42, -54, -25, 35, 78, 54, 40, 75, 15, -83, -60, 
  -69, 0, -77, 32, -39, 36, 6, 46, -88, 72, 14, 3, 13, 59, -8, 37, 
  21, -34, -89, 50, -87, -21, 28, 106, -86, -76, -89, -89, -86, -59, 30, 59, 
  47, -91, -91, -30, 17, 48, 38, 41, -12, -7, -50, -52, -85, 24, -49, -52, 
  -14, -82, -52, 93, 72, 16, 79, 53, 89, 55, 26, 76, 48, 5, 76, -52, 
  96, 42, -85, -35, 63, -71, -85, 31, 61, -42, 14, -21, -85, -69, 70, -28, 
  -12, 8, -11, 43, -18, 79, 47, -38, 84, -52, 81, -81, -58, -37, -67, 60, 
  93, -73, 127, -70, -4, -14, 75, -71, 41, 31, -55, 76, 69, -85, 59, -47, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 9,16 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0050063971430063248, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[16] = { -9, 0, -3, -2, 7, 5, 0, -5, -1, 13, -4, -1, -4, 0, -1, -10, };
const TfArray<1, int> tensor_dimension3 = { 1, { 16 } };
const TfArray<1, float> quant3_scale = { 1, { 0.024069709703326225, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[16*32] = { 
  33, 39, 86, 46, -21, -14, 2, 40, -4, 20, 0, -15, -49, 5, 71, -89, 28, 47, 21, 12, -79, -44, 57, 3, -7, 41, 83, 70, 51, -25, -3, -90, 
  -46, 74, 3, 65, -6, -76, -24, 39, -61, -20, -41, 4, 69, 91, 53, 90, 79, 14, 28, -90, -48, -61, -2, -1, 14, 38, 53, -25, -91, -80, 85, -38, 
  -18, 33, -35, 7, 20, -35, 10, 51, 93, 7, 69, 58, 48, -91, 0, 91, -71, 42, 45, -63, -29, 8, 72, -1, 103, 76, -63, 7, -77, 39, 85, 69, 
  48, -58, 42, -47, 57, -33, -76, 35, 18, -82, -22, 72, -11, -62, -52, 27, -63, 3, -37, -48, 43, -23, 57, 43, 59, -73, 43, -7, -13, -79, -71, -15, 
  -37, -55, -64, -55, -86, -70, 19, 29, -70, -28, -40, -58, -25, 51, 25, -20, 48, 62, 63, -48, -78, 87, -30, 19, -83, -53, -30, 30, 45, 61, 86, -70, 
  -72, 55, 50, 44, -43, -98, -43, 66, -77, 46, -30, -36, 45, 57, -79, -27, -58, 94, 47, 28, 5, 13, -63, 50, -12, 59, -1, -19, 28, -32, -40, -56, 
  75, -2, 33, 57, -86, -22, 26, 17, 40, -67, 49, -82, -27, -7, 21, 55, -32, -89, -59, 65, -16, 18, -71, -70, -57, -24, 86, -35, -82, 33, -61, -35, 
  -12, 77, -2, -91, -87, 66, 82, 30, 51, 73, 70, 86, 40, 60, 44, 54, 13, 3, -59, -18, 84, 31, 87, 32, -44, 80, -14, -89, 55, -55, 56, -6, 
  51, -79, 81, 61, 13, -24, 74, 49, -34, -57, -71, 59, 71, -25, -95, 89, -20, -46, 67, 50, 14, 48, -26, -17, 19, -93, 91, -2, -12, -98, 59, -41, 
  36, -57, 44, 59, -59, 60, 63, 39, -22, -37, -15, -55, 0, 44, -27, 34, -7, -56, -39, 73, -26, 42, -35, 76, 9, 77, -71, -72, -71, 69, -14, 84, 
  -63, -48, -39, 12, 2, -62, 51, -31, -86, -78, -21, -13, -54, -91, -66, 26, -49, -6, -38, 35, -64, 43, -27, 78, -21, 15, -24, 75, 7, 27, 65, 56, 
  -93, 38, -54, 71, 54, -2, -48, -70, -44, -55, 28, 11, 82, -106, -6, 33, -26, -10, -73, 48, -80, -85, -71, -36, 87, 55, 29, -74, 46, -79, 35, -101, 
  -79, 45, -69, 75, -55, -40, 78, -35, 44, -14, -80, -39, -98, 35, -79, -31, 51, 50, 60, 5, 41, -89, -50, 39, -100, -77, -52, -27, 5, 28, 14, 12, 
  11, -13, -25, -43, -91, 60, -49, -42, 57, 41, -44, 2, -93, -79, -50, -72, -42, 15, 85, -4, 66, -75, -65, 56, -17, 8, 3, -80, 64, -52, 11, -3, 
  49, 10, 66, -66, -60, 15, 15, -97, -11, 78, 82, 20, -20, -41, 51, -64, 76, -92, 12, 57, 16, -81, 3, -77, 48, -40, -20, -38, -127, 47, 9, -64, 
  57, 55, -9, -39, 3, -42, -43, 55, -3, -15, 51, -25, -7, -53, 9, 33, -54, -73, 59, -57, -91, -13, 20, 49, 35, -33, 50, -56, 12, 78, -15, 51, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 16,32 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0037041350733488798, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[32] = { 0, 0, 0, 2, -6, 1, 0, 0, 0, 0, 0, 0, 1, 6, 0, 0, 0, 0, 0, 5, 0, 0, 0, -1, 0, 4, -8, 0, -6, 2, 0, -1, };
const TfArray<1, int> tensor_dimension5 = { 1, { 32 } };
const TfArray<1, float> quant5_scale = { 1, { 0.047494757920503616, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[32*35] = { 
  0, -63, -41, 53, -8, 22, 31, 12, 15, 11, 16, -22, -15, -55, 58, -60, -21, 44, -46, 36, 39, 59, -32, 19, -43, 29, 10, -24, -7, -23, -42, 65, 47, -12, 33, 
  -64, -66, -3, 48, -60, 29, 15, -24, -23, -42, 51, -11, 6, 35, 13, 33, -66, -9, -5, -29, 56, -63, -61, 62, -9, -27, 32, -18, 20, 42, 5, 40, -9, 60, -39, 
  42, -55, -36, 32, 38, 62, 22, -5, -56, 31, 21, 8, 51, -33, -60, 8, -39, -54, -59, -63, 33, 40, 38, 18, -51, 33, 53, 3, 2, 5, 23, -28, 54, 29, 47, 
  -64, 46, 46, -21, 65, 32, 5, 58, 41, -29, -54, 29, 61, -41, 90, 67, 28, 45, 23, -6, 38, 51, -45, -44, 33, -54, -31, 46, 0, 15, 39, 45, -18, -55, 43, 
  57, -38, -7, 35, -39, -31, 3, 37, -45, -26, 35, -33, 13, 44, -105, -85, -86, -70, -58, -28, 119, -79, -58, 8, -95, 6, -11, 36, 53, 60, -13, -26, -64, -14, 18, 
  -15, 37, 0, 15, -55, -25, -18, -33, 24, -1, -47, 17, -42, -16, 2, 53, -46, 25, -48, 20, 41, 28, 32, 6, 65, 45, -19, 6, -17, -3, -2, 32, 62, -24, 50, 
  32, -17, -63, -34, -29, -23, -23, 20, 32, -64, -26, -39, 14, -61, -33, -26, -57, -21, -51, 66, 1, -59, 58, -4, 52, -7, 13, -20, -12, -25, -6, -60, -41, -1, -50, 
  25, 27, -42, 15, -8, -21, 49, 37, 17, 8, -45, -55, 2, 31, -36, 3, 19, 49, 42, 17, 18, -58, -32, -80, 0, -12, -45, -6, -50, -59, -39, 2, 44, -66, 31, 
  36, -14, -21, -49, -22, -5, -2, -61, -29, -23, 27, -32, -18, 60, 25, 40, -32, -32, -52, 24, -10, -61, 41, -60, -29, -33, -49, -32, -41, 51, -34, -12, -58, -17, -9, 
  -55, 53, -4, -52, -26, -36, -42, 17, 30, -47, -7, 66, -24, -54, -48, 66, -12, 56, 64, -9, -48, 44, 16, -38, 46, 15, 63, -47, -64, 6, 56, -59, 31, -27, 19, 
  63, -56, 13, -64, -43, -4, -49, -65, 38, -49, -1, 1, -52, 12, -36, 54, 62, -54, 17, 30, -52, -12, -44, 27, -51, 25, -61, 42, -56, 66, 38, 33, 29, 40, 42, 
  -9, -35, -62, 19, 20, 48, 53, 25, 25, -1, -27, 22, 39, -42, 52, 20, -47, -24, -10, -46, 3, 39, 14, 18, 4, 29, 1, -47, -7, -61, -57, -43, -6, 10, 30, 
  -32, 8, -7, 39, -42, -53, -34, -32, -35, 46, -3, -6, -21, 30, 57, 78, 93, 96, -57, 20, -78, -38, -51, 39, -59, -8, -57, 33, 19, 57, -10, 41, -8, -41, 27, 
  3, -1, 33, 26, 20, -9, -121, 50, -31, -49, -80, -20, -36, -19, 65, 49, 95, 98, 30, 61, -109, 40, 90, 75, -4, 61, -45, -80, -66, -45, 65, 57, -38, -62, -126, 
  59, -23, -64, -26, 55, 31, -3, -25, -51, 45, -58, 64, 25, 31, -51, -62, 65, -19, 44, 43, -30, -51, 52, -51, -50, -66, -5, 34, 45, -52, -64, -43, -56, -4, -53, 
  0, 18, -32, -58, 63, 24, -14, 52, 60, -15, 11, -44, 18, -14, -24, 15, -18, -28, 25, 27, -24, -24, 23, 16, 45, 38, 66, 37, -20, -42, -48, -45, 30, 22, -50, 
  1, 39, 18, -57, -16, 24, 4, -58, 35, 35, -52, 65, 56, 37, -11, 27, 47, -45, -17, -42, 51, -54, -41, -43, 38, 0, -59, -56, -26, 39, -5, -60, 26, 12, 63, 
  -12, -56, -19, 63, 65, 23, -56, 9, 18, -1, -46, 46, -11, -52, -33, -35, 3, -16, 5, -7, 2, 46, -52, -5, 57, -62, -36, 37, -32, -44, -50, 34, 2, -31, 39, 
  -55, 30, 28, -39, 46, -2, -50, -47, 63, -10, 4, 23, 65, 63, 42, -28, -31, -34, -18, -61, -42, 65, -56, 15, 65, -48, 3, 23, 40, -35, -52, -20, -12, -12, -7, 
  -13, 47, -16, 7, 26, 47, 7, 20, 19, -74, -13, 59, -43, 6, 69, 67, 112, 125, -36, 60, 7, 46, 92, -32, 6, -43, 57, 14, -40, -56, -6, -49, -13, 56, -90, 
  -9, 1, -52, -16, -39, -52, -15, -41, 32, -28, 47, 54, -7, -38, 27, 41, 5, -60, 47, -62, -54, 40, -20, -56, 6, -6, -53, 36, -53, -8, -47, 43, -51, -48, 31, 
  -4, -36, -22, -20, 0, 60, 12, -64, 46, 51, 32, -53, -51, -28, 61, 32, -44, -31, -38, -19, 63, -9, 44, -35, 10, -36, 54, 11, -43, 27, 0, 21, 22, 35, 12, 
  -9, -36, -40, 6, 11, -6, 63, 1, -46, -38, 38, 37, -31, 54, 51, -17, -10, 53, -45, -52, -47, -10, -59, -44, 18, 34, -63, -32, -10, -62, -17, -13, -56, -38, 58, 
  26, -57, 49, -30, -26, -55, 4, -31, -8, 22, -39, 23, 54, -53, -5, 26, -37, -70, 52, -14, -21, -13, -19, 7, 27, 40, 19, 30, -53, 30, 30, 27, -12, 22, 45, 
  9, -30, -60, 15, -64, 38, -55, 50, -2, 60, 55, 28, 60, 57, 31, -7, -22, 44, 16, 16, -45, 12, -26, 25, -9, 19, 11, -55, -23, 37, 44, 5, 65, -55, -62, 
  36, 46, -51, 8, 61, 14, -67, -78, 28, -58, 7, 60, -14, 10, 53, 57, 41, 72, -10, -64, -84, 13, 51, 24, -13, 25, 66, -71, 48, 37, 41, -30, -63, -9, -69, 
  -10, 43, -43, 48, 22, 5, 24, 23, -33, -20, -28, -36, -56, 121, -60, -114, -110, -61, -33, -36, 76, -2, -85, -29, -127, 14, -39, 63, -34, -42, -14, 4, -13, 34, 42, 
  -64, 3, -50, -6, 11, 55, -53, 42, 28, 51, -35, -35, -15, -42, 29, 62, -42, 66, -29, -23, -57, 6, -45, 12, 58, 18, 17, -34, -3, -16, 32, 17, 20, 15, -37, 
  46, 37, 23, 38, -47, -10, 91, -8, -69, 0, -55, -31, 31, 54, -116, -47, -120, -33, 30, -1, 67, -45, -20, -59, -70, -34, -20, 2, 48, -60, 20, -61, -65, -18, 5, 
  12, -9, 41, -11, 55, -66, 9, 51, 5, -28, 32, -39, -50, -24, 86, 66, 69, 11, -13, -50, -20, 25, 75, 72, -10, 27, 46, 37, -49, 62, -51, -7, -49, 29, -67, 
  15, -46, 4, -21, -6, 22, 11, -56, 26, -34, -1, 28, 55, -29, 52, -12, 32, 51, 44, -28, -14, -21, -52, -53, -22, -8, -11, -10, 63, 15, 25, -15, 21, 21, -46, 
  28, 45, -55, 24, -9, -15, 67, -38, -44, -28, -24, 41, -60, -20, -60, 18, 30, -21, 14, 10, -12, 6, -3, 42, -11, 47, 50, 61, 13, 18, -6, -2, 46, -21, -19, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 32,35 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0045292307622730732, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,32 } };
const TfArray<1, float> quant7_scale = { 1, { 6.4980649948120117, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,16 } };
const TfArray<1, float> quant8_scale = { 1, { 1.9568369388580322, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,9 } };
const TfArray<1, float> quant9_scale = { 1, { 1.1656033992767334, } };
const TfArray<1, int> quant9_zero = { 1, { -58 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 35, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 36, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 512, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1120, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 48), (TfLiteIntArray*)&g0::tensor_dimension7, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 9, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 9, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_827660_5_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_827660_5_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_827660_5_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_827660_5_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_827660_5_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
